QUESTIONS_3_4 = [
    {
        "id": 1,
        "topic": "POSSESSIVE_FAMILY",
        "topic_ru": "possessive adjectives: his / her; family: daughter / husband",
        "world_intro": "Наш первый мир – восточная сказка",
        "image": "01_daughter_his.png",
        "question": "Who are they?",
        "options": [
            {"text": "This is the Sultan and his daughter.", "correct": True},
            {"text": "This is the Sultan and her daughter.", "correct": False, "error": "HIS_HER", "meaning": "не различает притяжательные местоимения his / her"},
            {"text": "This is the Sultan and his husband.", "correct": False, "error": "FAMILY_DAUGHTER_HUSBAND", "meaning": "грамматически his выбрано правильно, но ребёнок не понимает или путает семейную лексику daughter / husband"},
        ],
    },
    {
        "id": 2,
        "topic": "BE_HAVE_APPEARANCE",
        "topic_ru": "am/is/are, have got/has got; feelings and appearance",
        "image": "02_eastern_princess_happy.png",
        "question": "Choose the correct sentence.",
        "options": [
            {"text": "She is happy and she has got long dark hair.", "correct": True},
            {"text": "She are happy and she have got long dark hair.", "correct": False, "error": "BE_HAVE_CONFUSION", "meaning": "путает формы is / are и have / has; пробел в базовых конструкциях"},
            {"text": "She is sad and she has got long fair hair.", "correct": False, "error": "FEELINGS_APPEARANCE", "meaning": "не помнит лексику по теме feelings: happy / sad и appearance"},
        ],
    },
    {
        "id": 3,
        "topic": "PRESENT_SIMPLE_CONTINUOUS",
        "topic_ru": "Present Simple vs Present Continuous; shopping / toys and objects",
        "image": "03_eastern_market_doll_five.png",
        "question": "Look! What is the man doing?",
        "options": [
            {"text": "He is selling a doll.", "correct": True},
            {"text": "He sells a doll now.", "correct": False, "error": "PRESENT_SIMPLE_FOR_NOW", "meaning": "путает Present Simple и Present Continuous"},
            {"text": "He is selling a ball.", "correct": False, "error": "DOLL_BALL", "meaning": "грамматика правильная, но путает doll / ball; возможно, не различает b / d при чтении или не знает слова по теме игрушек"},
        ],
    },
    {
        "id": 4,
        "topic": "PRESENT_SIMPLE_CONTINUOUS",
        "topic_ru": "Present Simple vs Present Continuous; clothes / daily routine",
        "world_intro": "Ой! Баба Яга и Кащей вклинулись в наше путешествие!",
        "image": "04_baba_yaga_koschei_getting_dressed.png",
        "question": "Look! What is Koschei doing?",
        "options": [
            {"text": "He’s getting dressed quickly.", "correct": True},
            {"text": "He gets dressed now.", "correct": False, "error": "PRESENT_SIMPLE_FOR_NOW", "meaning": "путает Present Simple и Present Continuous"},
            {"text": "He’s cleaning the room.", "correct": False, "error": "ACTION_VOCABULARY", "meaning": "грамматика понята, но ребёнок не понимает действие; пробел по текущей лексике clothes / daily routine"},
        ],
    },
    {
        "id": 5,
        "topic": "COMPARATIVE_ADJECTIVES",
        "topic_ru": "comparative adjectives; animals and appearance / size",
        "world_intro": "А сейчас мы в мире Зверополиса!",
        "image": "05_animal_city_fox_rabbit.png",
        "question": "Choose the correct sentence.",
        "options": [
            {"text": "The fox is taller than the rabbit.", "correct": True},
            {"text": "The fox is tall than the rabbit.", "correct": False, "error": "COMPARATIVE_FORM", "meaning": "не образует сравнительную степень"},
            {"text": "The fox is shorter than the rabbit.", "correct": False, "error": "TALL_SHORT", "meaning": "грамматика правильная, но путает tall / short"},
        ],
    },
    {
        "id": 6,
        "topic": "SUPERLATIVE_ADJECTIVES",
        "topic_ru": "superlative adjectives; adjectives",
        "image": "06_animal_city_sloth_drivers.png",
        "question": "Choose the correct sentence.",
        "options": [
            {"text": "The sloth is the fastest driver in the city.", "correct": True},
            {"text": "The sloth is the most fast driver in the city.", "correct": False, "error": "SUPERLATIVE_FORM", "meaning": "неправильно образует превосходную степень"},
            {"text": "The sloth is the longest driver in the city.", "correct": False, "error": "FAST_LONG", "meaning": "грамматика правильная, но путает fast / long"},
        ],
    },
    {
        "id": 7,
        "topic": "SOME_ANY",
        "topic_ru": "some / any; food",
        "world_intro": "Новый мир – мы пришли в Anime City",
        "image": "07_anime_city_girl_icecream.png",
        "question": "What does she want?",
        "options": [
            {"text": "Do you have any vanilla ice cream?", "correct": True},
            {"text": "Do you have some vanilla ice cream?", "correct": False, "error": "SOME_ANY_QUESTION", "meaning": "путает some / any в обычном вопросе"},
            {"text": "Do you have any vanilla cheese?", "correct": False, "error": "FOOD_ICE_CREAM_CHEESE", "meaning": "грамматика правильная, но путает названия еды"},
        ],
    },
    {
        "id": 8,
        "topic": "SOME_ANY",
        "topic_ru": "some в предложениях еды; food and drinks",
        "image": "08_anime_city_offer_icecream.png",
        "question": "Choose the correct sentence.",
        "options": [
            {"text": "Would you like some ice cream?", "correct": True},
            {"text": "Would you like any ice cream?", "correct": False, "error": "SOME_ANY_OFFER", "meaning": "не понимает употребление some / any в вопросах, просьбах и предложении чего-то"},
            {"text": "Wuld you like some ise cream?", "correct": False, "error": "SPELLING_WOULD_ICE", "meaning": "some / any выбрано верно и конструкция знакома, но есть ошибки в правописании"},
        ],
    },
    {
        "id": 9,
        "topic": "PAST_SIMPLE",
        "topic_ru": "Past Simple, irregular verbs; places / travelling",
        "image": "09_fantasy_anime_flying_girl.png",
        "question": "Where did they go yesterday?",
        "options": [
            {"text": "They went to the city.", "correct": True},
            {"text": "They goed to the city.", "correct": False, "error": "PAST_GO_WENT", "meaning": "не знает неправильную форму go → went"},
            {"text": "They went to the forest.", "correct": False, "error": "CITY_FOREST", "meaning": "Past Simple правильный, но путает city / forest"},
        ],
    },
    {
        "id": 10,
        "topic": "PAST_SIMPLE",
        "topic_ru": "Past Simple questions, did + base form; activities / travelling",
        "image": "10_fantasy_anime_climbing_traveler.png",
        "question": "He was in the mountains last summer. Choose the correct question.",
        "options": [
            {"text": "Did you climb last summer?", "correct": True},
            {"text": "Did you climbed last summer?", "correct": False, "error": "PAST_DID_BASE_FORM", "meaning": "после did оставляет форму Past Simple"},
            {"text": "Did you swim last summer?", "correct": False, "error": "CLIMB_SWIM", "meaning": "грамматика правильная, но путает climb / swim"},
        ],
    },
    {
        "id": 11,
        "topic": "WAS_WERE",
        "topic_ru": "was / were; pets / home / rooms",
        "world_intro": "Новый мир – Хогвартс!",
        "image": "11_magic_school_cat_on_bed.png",
        "question": "2 minutes ago the cat ...",
        "options": [
            {"text": "was in the bedroom.", "correct": True},
            {"text": "were on the bed.", "correct": False, "error": "WAS_WERE", "meaning": "путает was / were"},
            {"text": "is in the living room", "correct": False, "error": "PAST_PRESENT_ROOMS", "meaning": "не переключается с настоящего времени на прошлое и не различает living room / bedroom"},
        ],
    },
    {
        "id": 12,
        "topic": "THERE_WAS_WERE",
        "topic_ru": "there was / there were; furniture",
        "image": "12_magic_school_two_books_table.png",
        "question": "Yesterday in the library…",
        "options": [
            {"text": "There were two books on the table.", "correct": True},
            {"text": "There was two books on the table.", "correct": False, "error": "THERE_WAS_WERE_NUMBER", "meaning": "путает there was / there were"},
            {"text": "There two chairs were on the table.", "correct": False, "error": "THERE_WORD_ORDER_FURNITURE", "meaning": "путает порядок слов в конструкции и слова по теме мебель"},
        ],
    },
    {
        "id": 13,
        "topic": "MUST_MUSTNT",
        "topic_ru": "must / mustn’t; school things / actions",
        "image": "13_magic_school_golden_ball.png",
        "question": "Toto found the Golden Snitch. But…",
        "options": [
            {"text": "He mustn’t take the Snitch.", "correct": True},
            {"text": "He don’t must touch the Snitch.", "correct": False, "error": "MUST_NEGATIVE_FORM", "meaning": "неправильно образует отрицание с must"},
            {"text": "He mustn’t feed the Snitch.", "correct": False, "error": "TAKE_FEED", "meaning": "грамматика правильная, но путает take / feed"},
        ],
    },
    {
        "id": 14,
        "topic": "MUST_MUSTNT",
        "topic_ru": "must + base verb; housework",
        "world_intro": "Снова Яга и Кащей!",
        "image": "14_baba_yaga_koschei_housework.png",
        "question": "What must Koschei do?",
        "options": [
            {"text": "He must wash the dishes.", "correct": True},
            {"text": "He must to wash the dishes.", "correct": False, "error": "MUST_BASE_VERB", "meaning": "ставит to после must"},
            {"text": "He must have a shower.", "correct": False, "error": "HOUSEWORK_VOCABULARY", "meaning": "грамматика правильная, но путает wash the dishes / have a shower"},
        ],
    },
    {
        "id": 15,
        "topic": "PRESENT_SIMPLE",
        "topic_ru": "Present Simple, 3rd person singular; clothes",
        "image": "15_nu_pogodi_wolf_tshirt.png",
        "question": "Choose the correct sentence.",
        "options": [
            {"text": "The Wolf wears a T-shirt every day.", "correct": True},
            {"text": "The Wolf wear a T-shirt every day.", "correct": False, "error": "PRESENT_SIMPLE_3SG", "meaning": "забывает -s в 3-м лице"},
            {"text": "The Wolf wears a jacket every day.", "correct": False, "error": "TSHIRT_JACKET", "meaning": "грамматика правильная, но путает одежду"},
        ],
    },
    {
        "id": 16,
        "topic": "PRESENT_SIMPLE",
        "topic_ru": "Present Simple questions; daily routine / food",
        "image": "16_nu_pogodi_hare_eating.png",
        "question": "Choose the correct question.",
        "options": [
            {"text": "Does the Hare usually have lunch at one o’clock?", "correct": True},
            {"text": "Is the Hare usually have lunch at one o’clock?", "correct": False, "error": "DOES_VS_BE", "meaning": "не понимает, как задавать вопросы в этом времени, и путает вспомогательные глаголы"},
            {"text": "Does the Hare usually do lunch at one o’clock?", "correct": False, "error": "HAVE_DO_LUNCH", "meaning": "грамматика правильная, но не усвоено устойчивое выражение have lunch"},
        ],
    },
    {
        "id": 17,
        "topic": "MUCH_MANY",
        "topic_ru": "much / many, countable nouns; animals",
        "world_intro": "Ого! Роблокс! Погнали вперед!",
        "image": "17_block_game_three_foxes.png",
        "question": "Choose the correct question.",
        "options": [
            {"text": "How many foxes are there?", "correct": True},
            {"text": "How much foxes are there?", "correct": False, "error": "MUCH_MANY", "meaning": "путает much / many"},
            {"text": "How many foxs is there?", "correct": False, "error": "PLURAL_AGREEMENT_SPELLING", "meaning": "понимает many, но путает множественное число, is / are и написание множественного числа"},
        ],
    },
    {
        "id": 18,
        "topic": "QUANTIFIERS",
        "topic_ru": "not much / not many / a lot of; food and animals",
        "image": "18_block_game_mouse_cheese.png",
        "question": "Choose the correct sentence.",
        "options": [
            {"text": "There is a lot of cheese for the mouse.", "correct": True},
            {"text": "There isn’t much cheese for the mouse.", "correct": False, "error": "QUANTITY_MEANING", "meaning": "неверно определяет количество: not much / a lot of"},
            {"text": "There are many eggs for the mouse.", "correct": False, "error": "CHEESE_EGGS", "meaning": "не знает значение слов cheese / eggs"},
        ],
    },
    {
        "id": 19,
        "topic": "FUTURE_FORMS",
        "topic_ru": "be going to — plans / intentions; places and buildings",
        "world_intro": "Наконец мы добрались до Майнкрафта",
        "image": "19_minecraft_build_house.png",
        "question": "It’s evening. What is the boys’ plan?",
        "options": [
            {"text": "They are going to build a house.", "correct": True},
            {"text": "They will build a house.", "correct": False, "error": "GOING_TO_VS_WILL", "meaning": "не различает заранее запланированное действие и спонтанное решение"},
            {"text": "They will build a garden.", "correct": False, "error": "FUTURE_HOUSE_GARDEN", "meaning": "конструкция неправильная, плюс ребёнок путает house / garden"},
        ],
    },
    {
        "id": 20,
        "topic": "FUTURE_FORMS",
        "topic_ru": "will / won’t vs be going to; actions and injuries",
        "image": "20_minecraft_creeper.png",
        "question": "Oh no! A Creeper is coming! What does his friend say?",
        "options": [
            {"text": "I’ll help you! He won’t hurt us.", "correct": True},
            {"text": "I will helping you! He won’t hurts us.", "correct": False, "error": "WILL_BASE_VERB", "meaning": "не знает, что после will / won’t нужен глагол в начальной форме"},
            {"text": "I’ll help you! He won’t fall down.", "correct": False, "error": "HURT_FALL_DOWN", "meaning": "понимает грамматику, но не знает глаголы про травмы и путает hurt / fall down"},
        ],
    },
]
