QUESTIONS_5_6 = [
    {
        "id": 1,
        "topic": "POSSESSIVE_BE_HAVE",
        "topic_ru": "possessive adjectives: his / her; is / has got; family and accessories",
        "world_intro": "Wow! We are in an Arabian city.",
        "image": "01_daughter_his.png",
        "question": "This is the Sultan and his daughter.",
        "options": [
            {"text": "Her necklace is beautiful.", "correct": True},
            {"text": "His necklace is beautiful.", "correct": False, "error": "HIS_HER", "meaning": "не различает his / her"},
            {"text": "She is a beautiful necklace.", "correct": False, "error": "BE_HAVE_CONFUSION", "meaning": "путает to be / have got; вероятно, не помнит слово necklace и/или daughter"},
        ],
    },
    {
        "id": 2,
        "topic": "HOW_MUCH_NUMBERS",
        "topic_ru": "понимание How much...?; numbers 21–100 and shopping",
        "image": "02_eastern_market_doll_47.png",
        "question": "How much is the doll?",
        "options": [
            {"text": "It is forty-seven coins.", "correct": True},
            {"text": "It is on the table.", "correct": False, "error": "HOW_MUCH_VS_WHERE", "meaning": "не распознаёт, что How much? спрашивает о цене, и отвечает на Where?"},
            {"text": "It is a beautiful doll.", "correct": False, "error": "HOW_MUCH_FUNCTION", "meaning": "понимает отдельные слова или картинку, но не понимает коммуникативную функцию вопроса"},
        ],
    },
    {
        "id": 3,
        "topic": "PRESENT_SIMPLE_TRAVEL",
        "topic_ru": "Present Simple, 3rd person singular; travel and transport",
        "image": "03_eastern_boy_magic_carpet.png",
        "question": "How does he usually travel around the city?",
        "options": [
            {"text": "He usually flies on a magic carpet.", "correct": True},
            {"text": "He usually flys on a magic carpet.", "correct": False, "error": "PRESENT_SIMPLE_3SG_SPELLING", "meaning": "не помнит правила правописания -es в 3-м лице Present Simple"},
            {"text": "He usually drives a magic carpet.", "correct": False, "error": "TRAVEL_DRIVE_FLY", "meaning": "грамматическую форму строит правильно, но не различает travel / drive / fly и, возможно, carpet"},
        ],
    },
    {
        "id": 4,
        "topic": "PRESENT_CONTINUOUS_TRAVEL",
        "topic_ru": "Present Continuous vs Present Simple; by air / on foot",
        "world_intro": "🐾 Who is this? Baba Yaga?",
        "image": "04_baba_yaga_magic_carpet.png",
        "question": "How is Baba Yaga travelling now?",
        "options": [
            {"text": "She is travelling by air.", "correct": True},
            {"text": "She travels by air.", "correct": False, "error": "PRESENT_SIMPLE_FOR_NOW", "meaning": "выбирает Present Simple вместо действия right now"},
            {"text": "She is traveling on foot.", "correct": False, "error": "BY_AIR_ON_FOOT", "meaning": "грамматика правильная, но не понимает способ передвижения by air / on foot"},
        ],
    },
    {
        "id": 5,
        "topic": "PRESENT_SIMPLE_NEGATIVE",
        "topic_ru": "Present Simple questions and negatives; cereal / sausages",
        "image": "05_baba_yaga_breakfast.png",
        "question": "Does Baba Yaga have cereal for breakfast?",
        "options": [
            {"text": "No, she doesn't. She has sausages for breakfast.", "correct": True},
            {"text": "No, she don't. She has sausages for breakfast.", "correct": False, "error": "DOESNT_AGREEMENT", "meaning": "не умеет строить отрицание с doesn't и не согласует вспомогательный глагол с she"},
            {"text": "Yes, she does. She has cereal for breakfast.", "correct": False, "error": "CEREAL_SAUSAGES", "meaning": "форму ответа знает, но не понимает вопрос или лексику cereal / sausages"},
        ],
    },
    {
        "id": 6,
        "topic": "CAN_CLOTHES",
        "topic_ru": "can + bare infinitive; clothes and personal things",
        "world_intro": "🐾 Wow! Hogwarts! They play sports here!",
        "image": "06_magic_school_flying_match.png",
        "question": "What can the player wear for the match?",
        "options": [
            {"text": "He can wear gloves and a helmet.", "correct": True},
            {"text": "He can wears gloves and a helmet.", "correct": False, "error": "CAN_BASE_VERB", "meaning": "ставит -s после can и не знает, что после can используется базовая форма глагола"},
            {"text": "He can wear high heels and a handbag.", "correct": False, "error": "CLOTHES_EQUIPMENT", "meaning": "грамматику понимает, но путает лексику одежды и экипировки"},
        ],
    },
    {
        "id": 7,
        "topic": "THERE_IS_ARE_SOME_ANY",
        "topic_ru": "there is / there are; some / any; mushrooms / onions",
        "image": "07_magic_school_potion.png",
        "question": "Are there any mushrooms on the table?",
        "options": [
            {"text": "Yes, there are some mushrooms.", "correct": True},
            {"text": "Yes, there is some mushrooms.", "correct": False, "error": "THERE_IS_ARE_NUMBER", "meaning": "не согласует конструкцию there is / there are с существительным во множественном числе"},
            {"text": "Yes, there are any mushrooms.", "correct": False, "error": "SOME_ANY", "meaning": "понимает there are, но не различает типичное употребление some / any"},
        ],
    },
    {
        "id": 8,
        "topic": "COMPARATIVE_ADJECTIVES",
        "topic_ru": "comparative adjectives; clothes and appearance",
        "world_intro": "🐾 Now we are in Zootopia.",
        "image": "08_animal_city_fox_rabbit.png",
        "question": "Who is taller?",
        "options": [
            {"text": "The fox in the green shirt is taller than the rabbit.", "correct": True},
            {"text": "The fox in the green shirt is more tall than the rabbit.", "correct": False, "error": "COMPARATIVE_FORM", "meaning": "неправильно образует сравнительную степень короткого прилагательного"},
            {"text": "The rabbit is taller than the fox in the green shirt.", "correct": False, "error": "TALLER_MEANING", "meaning": "форму taller than распознаёт, но ошибается в значении"},
        ],
    },
    {
        "id": 9,
        "topic": "SUPERLATIVE_ADJECTIVES",
        "topic_ru": "superlative adjectives; jobs and transport",
        "image": "09_animal_city_sloth_drivers.png",
        "question": "Who is the fastest driver in the city?",
        "options": [
            {"text": "The sloth in the red car is the fastest driver in the city.", "correct": True},
            {"text": "The sloth in the red car is the faster driver in the city.", "correct": False, "error": "COMPARATIVE_SUPERLATIVE", "meaning": "путает comparative и superlative"},
            {"text": "The sloth in the red car is the slowest driver in the city.", "correct": False, "error": "FAST_SLOW", "meaning": "грамматическая форма построена правильно, но ребёнок путает fast / slow driver и контекст"},
        ],
    },
    {
        "id": 10,
        "topic": "SUPERLATIVE_ADVERBS",
        "topic_ru": "superlative adverbs: the highest / the loudest; fly high / sing loudly",
        "world_intro": "🐾 Wait... Baba Yaga is here again! She wants to be the best at everything!",
        "image": "10_baba_yaga_highest_loudest.png",
        "question": "Look at Baba Yaga!",
        "options": [
            {"text": "She can fly the highest and sing the loudest.", "correct": True},
            {"text": "She can fly the most high and sing the most loud.", "correct": False, "error": "SUPERLATIVE_ADVERB_FORM", "meaning": "не знает способ образования степеней сравнения коротких наречий"},
            {"text": "She can fly the loudest and sing the highest.", "correct": False, "error": "HIGH_LOUD", "meaning": "форму распознаёт, но путает смысл high / loud"},
        ],
    },
    {
        "id": 11,
        "topic": "ENJOY_GERUND_QUESTION",
        "topic_ru": "Present Simple question word order; enjoy + gerund",
        "world_intro": "🐾 Now Anime City!",
        "image": "11_anime_city_offer_icecream.png",
        "question": "What does she ask?",
        "options": [
            {"text": "Do you enjoy eating ice cream?", "correct": True},
            {"text": "Do enjoy you eating ice cream?", "correct": False, "error": "QUESTION_WORD_ORDER", "meaning": "не понимает порядок слов в вопросительном предложении"},
            {"text": "Do you enjoy to eat ice cream?", "correct": False, "error": "ENJOY_GERUND", "meaning": "вопросительную конструкцию строит правильно, но не знает enjoy + V-ing"},
        ],
    },
    {
        "id": 12,
        "topic": "FEW_LITTLE",
        "topic_ru": "a few / few / a little / little; travel and food",
        "image": "12_anime_found_food.png",
        "question": "Paimon says:\nWe have got enough food for the trip.\nAether says:",
        "options": [
            {"text": "We have got a few apples and a little bread.", "correct": True},
            {"text": "We have got a little apples and a few bread.", "correct": False, "error": "COUNTABLE_UNCOUNTABLE", "meaning": "путает countable / uncountable nouns"},
            {"text": "We have got few apples and little bread.", "correct": False, "error": "FEW_LITTLE_MEANING", "meaning": "формы выбирает по типу существительного верно, но не понимает, что без a появляется значение «почти нет / недостаточно»"},
        ],
    },
    {
        "id": 13,
        "topic": "REFLEXIVE_PRONOUNS",
        "topic_ru": "reflexive pronouns: himself / herself; protect / attack",
        "image": "13_anime_battle.png",
        "question": "What is he doing?",
        "options": [
            {"text": "He is protecting himself from the attack.", "correct": True},
            {"text": "He is protecting him from the attack.", "correct": False, "error": "REFLEXIVE_REQUIRED", "meaning": "воспринимает объект как другого человека и не понимает возвратное значение"},
            {"text": "He is protecting herself from the attack.", "correct": False, "error": "HIMSELF_HERSELF", "meaning": "понимает принцип reflexive pronoun, но не согласует его с субъектом he"},
        ],
    },
    {
        "id": 14,
        "topic": "HAVE_TO_HAS_TO",
        "topic_ru": "have to / has to; control / fight / mechanism / tail",
        "world_intro": "🐾 Dragons!",
        "image": "14_hiccup_tail_mechanism.png",
        "question": "What does Hiccup have to do when they fly together?",
        "options": [
            {"text": "He has to control the mechanism on Toothless’s tail.", "correct": True},
            {"text": "He have to control the mechanism on Toothless’s tail.", "correct": False, "error": "HAVE_TO_HAS_TO", "meaning": "не согласует have to с he"},
            {"text": "He must control the mechanism on Toothless’s tail.", "correct": False, "error": "CONTROL_FIGHT", "meaning": "грамматику строит правильно, но путает control / fight"},
        ],
    },
    {
        "id": 15,
        "topic": "MUSTNT_DONT_HAVE_TO_NEEDNT",
        "topic_ru": "mustn’t / don’t have to / needn’t; club / secret / rider",
        "image": "15_dragon_flight_club_secret.png",
        "question": "Dragon Flight Club is secret.",
        "options": [
            {"text": "They mustn’t tell anyone about the club.", "correct": True},
            {"text": "They don’t have to tell anyone about the club.", "correct": False, "error": "PROHIBITION_VS_NO_NECESSITY", "meaning": "не различает «нельзя рассказывать» и «необязательно рассказывать»"},
            {"text": "They needn’t tell anyone about the club.", "correct": False, "error": "NEEDNT_MEANING", "meaning": "не понимает значение needn't и воспринимает отсутствие необходимости как запрет"},
        ],
    },
    {
        "id": 16,
        "topic": "SHOULD",
        "topic_ru": "should + bare infinitive; household chores",
        "world_intro": "🐾 Oh, it is Baba Yaga and Koschei!",
        "image": "16_baba_yaga_koschei_housework.png",
        "question": "The dishes are dirty. What should Koschei do?",
        "options": [
            {"text": "He should wash the dishes.", "correct": True},
            {"text": "He should to wash the dishes.", "correct": False, "error": "SHOULD_BASE_VERB", "meaning": "ставит to после should и не знает форму глагола после модального should"},
            {"text": "He should cleans the dishes", "correct": False, "error": "SHOULD_AND_HOUSEWORK", "meaning": "не понимает модальную конструкцию и путает wash the dishes / clean the room"},
        ],
    },
    {
        "id": 17,
        "topic": "WANT_TO_LET",
        "topic_ru": "want + to V; let somebody + V; battle / take part / join a team",
        "world_intro": "🐾 Wow! Now we are inside a comic book!",
        "image": "17_superhero_join_battle.png",
        "question": "Miles wants to take part in the battle.",
        "options": [
            {"text": "Peter lets him join his team.", "correct": True},
            {"text": "Peter lets him joining his team.", "correct": False, "error": "LET_GERUND", "meaning": "ставит gerund после let вместо bare infinitive"},
            {"text": "Peter lets him to join his team.", "correct": False, "error": "LET_TO_INFINITIVE", "meaning": "знает want to, но не знает, что после let + object to не используется"},
        ],
    },
    {
        "id": 18,
        "topic": "FUTURE_ARRANGEMENT",
        "topic_ru": "Present Continuous for fixed future arrangements vs will / be going to",
        "image": "18_miles_meets_gwen_tuesday.png",
        "question": "What is Miles doing on Tuesday?",
        "options": [
            {"text": "He is meeting Gwen on Tuesday.", "correct": True},
            {"text": "He will meet Gwen on Tuesday.", "correct": False, "error": "ARRANGEMENT_VS_WILL", "meaning": "не различает spontaneous / future prediction и заранее согласованную встречу; фраза возможна в другом контексте, но не выражает проверяемую школьную функцию"},
            {"text": "He is going to meet Gwen on Tuesday.", "correct": False, "error": "ARRANGEMENT_VS_INTENTION", "meaning": "понимает будущее намерение, но не различает intention и fixed arrangement; фраза возможна в другом контексте"},
        ],
    },
    {
        "id": 19,
        "topic": "FUTURE_PLANS",
        "topic_ru": "be going to for plans and intentions; build a house / blocks",
        "world_intro": "🐾 Hooray! Minecraft!",
        "image": "19_minecraft_build_house.png",
        "scene_hint": "They have all the blocks ready and they have already decided what to build.",
        "question": "They have a plan to build a house.",
        "options": [
            {"text": "They are going to build a house.", "correct": True},
            {"text": "They will build a house.", "correct": False, "error": "PLAN_VS_WILL", "meaning": "не различает заранее существующий план и другие функции will"},
            {"text": "They are going build a house.", "correct": False, "error": "GOING_TO_MISSING_TO", "meaning": "понимает значение конструкции, но пропускает to в полной форме be going to"},
        ],
    },
    {
        "id": 20,
        "topic": "FUTURE_DECISIONS",
        "topic_ru": "will for spontaneous decisions vs be going to / Present Continuous; help / suddenly",
        "image": "20_minecraft_creeper.png",
        "question": "O, no! It’s a Creeper! What does Steve say?",
        "options": [
            {"text": "I'll help you!", "correct": True},
            {"text": "I'm going to help you!", "correct": False, "error": "DECISION_VS_INTENTION", "meaning": "не распознаёт функцию on-the-spot decision и путает решение, принятое сейчас, с заранее существующим намерением"},
            {"text": "I'm helping you in a minute!", "correct": False, "error": "DECISION_VS_ARRANGEMENT", "meaning": "не различает спонтанное решение сейчас и заранее организованное действие в будущем"},
        ],
    },
]
