QUESTIONS_5_6 = [
    {
        "id": 1,
        "topic": "POSSESSIVE_BE_HAVE",
        "topic_ru": "possessive adjectives: his / her; is / has got; family and accessories",
        "world_intro": "Wow! We are in an Arabian city.",
        "image": "01_daughter_his.png",
        "question": "This is the Sultan and his daughter.",
        "options": [
            {"text": "Her necklace is beautiful.", "correct": True},
            {"text": "His necklace is beautiful.", "correct": False, "error": "HIS_HER", "meaning": "не различает his / her"},
            {"text": "She is a beautiful necklace.", "correct": False, "error": "BE_HAVE_CONFUSION", "meaning": "путает to be / have got; вероятно, не помнит слово necklace и/или daughter"},
        ],
    },
    {
        "id": 2,
        "topic": "HOW_MUCH_NUMBERS",
        "topic_ru": "понимание How much...?; numbers 21–100 and shopping",
        "image": "02_eastern_market_doll_47.png",
        "question": "How much is the doll?",
        "options": [
            {"text": "It is forty-seven coins.", "correct": True},
            {"text": "It is on the table.", "correct": False, "error": "HOW_MUCH_VS_WHERE", "meaning": "не распознаёт, что How much? спрашивает о цене, и отвечает на Where?"},
            {"text": "It is a beautiful doll.", "correct": False, "error": "HOW_MUCH_FUNCTION", "meaning": "понимает отдельные слова или картинку, но не понимает коммуникативную функцию вопроса"},
        ],
    },
    {
        "id": 3,
        "topic": "PRESENT_SIMPLE_TRAVEL",
        "topic_ru": "Present Simple, 3rd person singular; travel and transport",
        "image": "03_eastern_boy_magic_carpet.png",
        "question": "How does he usually travel around the city?",
        "options": [
            {"text": "He usually flies on a magic carpet.", "correct": True},
            {"text": "He usually flys on a magic carpet.", "correct": False, "error": "PRESENT_SIMPLE_3SG_SPELLING", "meaning": "не помнит правила правописания -es в 3-м лице Present Simple"},
            {"text": "He usually drives a magic carpet.", "correct": False, "error": "TRAVEL_DRIVE_FLY", "meaning": "грамматическую форму строит правильно, но не различает travel / drive / fly и, возможно, carpet"},
        ],
    },
    {
        "id": 4,
        "topic": "PRESENT_CONTINUOUS_TRAVEL",
        "topic_ru": "Present Continuous vs Present Simple; by air / on foot",
        "world_intro": "🐾 Who is this? Baba Yaga?",
        "image": "04_baba_yaga_magic_carpet.png",
        "question": "How is Baba Yaga travelling now?",
        "options": [
            {"text": "She is travelling by air.", "correct": True},
            {"text": "She travels by air.", "correct": False, "error": "PRESENT_SIMPLE_FOR_NOW", "meaning": "выбирает Present Simple вместо действия right now"},
            {"text": "She is traveling on foot.", "correct": False, "error": "BY_AIR_ON_FOOT", "meaning": "грамматика правильная, но не понимает способ передвижения by air / on foot"},
        ],
    },
    {
        "id": 5,
        "topic": "PRESENT_SIMPLE_NEGATIVE",
        "topic_ru": "Present Simple questions and negatives; cereal / sausages",
        "image": "05_baba_yaga_breakfast.png",
        "question": "Does Baba Yaga have cereal for breakfast?",
        "options": [
            {"text": "No, she doesn't. She has sausages for breakfast.", "correct": True},
            {"text": "No, she don't. She has sausages for breakfast.", "correct": False, "error": "DOESNT_AGREEMENT", "meaning": "не умеет строить отрицание с doesn't и не согласует вспомогательный глагол с she"},
            {"text": "Yes, she does. She has cereal for breakfast.", "correct": False, "error": "CEREAL_SAUSAGES", "meaning": "форму ответа знает, но не понимает вопрос или лексику cereal / sausages"},
        ],
    },
    {
        "id": 6,
        "topic": "CAN_CLOTHES",
        "topic_ru": "can + bare infinitive; clothes and personal things",
        "world_intro": "🐾 Wow! Hogwarts! They play sports here!",
        "image": "06_magic_school_flying_match.png",
        "question": "What can the player wear for the match?",
        "options": [
            {"text": "He can wear gloves and a helmet.", "correct": True},
            {"text": "He can wears gloves and a helmet.", "correct": False, "error": "CAN_BASE_VERB", "meaning": "ставит -s после can и не знает, что после can используется базовая форма глагола"},
            {"text": "He can wear high heels and a handbag.", "correct": False, "error": "CLOTHES_EQUIPMENT", "meaning": "грамматику понимает, но путает лексику одежды и экипировки"},
        ],
    },
    {
        "id": 7,
        "topic": "THERE_IS_ARE_SOME_ANY",
        "topic_ru": "there is / there are; some / any; mushrooms / onions",
        "image": "07_magic_school_potion.png",
        "question": "Are there any mushrooms on the table?",
        "options": [
            {"text": "Yes, there are some mushrooms.", "correct": True},
            {"text": "Yes, there is some mushrooms.", "correct": False, "error": "THERE_IS_ARE_NUMBER", "meaning": "не согласует конструкцию there is / there are с существительным во множественном числе"},
            {"text": "Yes, there are any mushrooms.", "correct": False, "error": "SOME_ANY", "meaning": "понимает there are, но не различает типичное употребление some / any"},
        ],
    },
    {
        "id": 8,
        "topic": "COMPARATIVE_ADJECTIVES",
        "topic_ru": "comparative adjectives; clothes and appearance",
        "world_intro": "🐾 Now we are in Zootopia.",
        "image": "08_animal_city_fox_rabbit.png",
        "question": "Who is taller?",
        "options": [
            {"text": "The fox in the green shirt is taller than the rabbit.", "correct": True},
            {"text": "The fox in the green shirt is more tall than the rabbit.", "correct": False, "error": "COMPARATIVE_FORM", "meaning": "неправильно образует сравнительную степень короткого прилагательного"},
            {"text": "The rabbit is taller than the fox in the green shirt.", "correct": False, "error": "TALLER_MEANING", "meaning": "форму taller than распознаёт, но ошибается в значении"},
        ],
    },
    {
        "id": 9,
        "topic": "SUPERLATIVE_ADJECTIVES",
        "topic_ru": "superlative adjectives; jobs and transport",
        "image": "09_animal_city_sloth_drivers.png",
        "question": "Who is the fastest driver in the city?",
        "options": [
            {"text": "The sloth in the red car is the fastest driver in the city.", "correct": True},
            {"text": "The sloth in the red car is the faster driver in the city.", "correct": False, "error": "COMPARATIVE_SUPERLATIVE", "meaning": "путает comparative и superlative"},
            {"text": "The sloth in the red car is the slowest driver in the city.", "correct": False, "error": "FAST_SLOW", "meaning": "грамматическая форма построена правильно, но ребёнок путает fast / slow driver и контекст"},
        ],
    },
    {
        "id": 10,
        "topic": "SUPERLATIVE_ADVERBS",
        "topic_ru": "superlative adverbs: the highest / the loudest; fly high / sing loudly",
        "world_intro": "🐾 Wait... Baba Yaga is here again! She wants to be the best at everything!",
        "image": "10_baba_yaga_highest_loudest.png",
        "question": "Look at Baba Yaga!",
        "options": [
            {"text": "She can fly the highest and sing the loudest.", "correct": True},
            {"text": "She can fly the most high and sing the most loud.", "correct": False, "error": "SUPERLATIVE_ADVERB_FORM", "meaning": "не знает способ образования степеней сравнения коротких наречий"},
            {"text": "She can fly the loudest and sing the highest.", "correct": False, "error": "HIGH_LOUD", "meaning": "форму распознаёт, но путает смысл high / loud"},
        ],
    },
    {
        "id": 11,
        "topic": "ENJOY_GERUND",
        "topic_ru": "enjoy + gerund; free time activities",
        "world_intro": "🐾 Now Anime City!",
        "image": "11_anime_city_friends_go_cycling.png",
        "question": "She likes to hang out with friends.",
        "options": [
            {"text": "They enjoy going cycling.", "correct": True},
            {"text": "They enjoy to go cycling.", "correct": False, "error": "ENJOY_GERUND", "meaning": "понимает лексику и смысл ситуации, но не знает, что после enjoy используется форма V-ing"},
            {"text": "They enjoy going windsurfing.", "correct": False, "error": "FREE_TIME_ACTIVITY", "meaning": "конструкцию enjoy + V-ing понимает, но не различает go cycling / go windsurfing и лексику по теме свободного времени"},
        ],
    },
    {
        "id": 12,
        "topic": "FEW_LITTLE",
        "topic_ru": "a few / few / a little / little; travel and food",
        "image": "12_anime_found_food.png",
        "question": "Paimon says: There is enough food for the trip.",
        "options": [
            {"text": "We have got a few apples and a little bread.", "correct": True},
            {"text": "We have got a little apples and a few bread.", "correct": False, "error": "COUNTABLE_UNCOUNTABLE", "meaning": "путает countable / uncountable nouns"},
            {"text": "We have got few apples and little bread.", "correct": False, "error": "FEW_LITTLE_MEANING", "meaning": "формы выбирает по типу существительного верно, но не понимает, что без a появляется значение «почти нет / недостаточно»"},
        ],
    },
    {
        "id": 13,
        "topic": "REFLEXIVE_PRONOUNS",
        "topic_ru": "reflexive pronouns: himself / herself; protect / attack / burglar / run",
        "image": "13_anime_battle.png",
        "question": "What is he doing?",
        "options": [
            {"text": "He is protecting himself from the attack.", "correct": True},
            {"text": "He is protecting him from the attack.", "correct": False, "error": "REFLEXIVE_REQUIRED", "meaning": "воспринимает объект как другого человека и не понимает возвратное значение"},
            {"text": "He is running himself from the burglar.", "correct": False, "error": "REFLEXIVE_CRIME_ACTIONS", "meaning": "не понимает употребление reflexive pronoun и путает лексику по теме действий и опасных ситуаций"},
        ],
    },
    {
        "id": 14,
        "topic": "HAVE_TO_HAS_TO",
        "topic_ru": "have to / has to / must; use / mechanism / tail",
        "world_intro": "🐾 Dragons!",
        "image": "14_hiccup_tail_mechanism.png",
        "question": "Hiccup can ride Toothless and fly, but…",
        "options": [
            {"text": "He has to use the mechanism on Toothless’s tail.", "correct": True},
            {"text": "He have to use the mechanism on Toothless’s tail.", "correct": False, "error": "HAVE_TO_HAS_TO", "meaning": "не согласует have to с he; смысл конструкции have to при этом может понимать"},
            {"text": "He mustn’t use the mechanism on Toothless’s tail.", "correct": False, "error": "HAVE_TO_VS_MUSTNT", "meaning": "не различает обязанность и запрет в конструкциях has to / mustn’t; возможно, не понял глагол действия или контекст"},
        ],
    },
    {
        "id": 15,
        "topic": "MUSTNT_DONT_HAVE_TO_NEEDNT",
        "topic_ru": "mustn’t / don’t have to / needn’t; club / secret / rider",
        "image": "15_dragon_flight_club_secret.png",
        "question": "Dragon Flying Club is secret.",
        "options": [
            {"text": "They mustn’t tell anyone about the club.", "correct": True},
            {"text": "They don’t have to tell anyone about the club.", "correct": False, "error": "PROHIBITION_VS_NO_NECESSITY", "meaning": "не различает «нельзя рассказывать» и «необязательно рассказывать»"},
            {"text": "They needn’t tell anyone about the club.", "correct": False, "error": "NEEDNT_MEANING", "meaning": "не понимает значение needn't и воспринимает отсутствие необходимости как запрет"},
        ],
    },
    {
        "id": 16,
        "topic": "SHOULD",
        "topic_ru": "should + bare infinitive / wants to; household chores and emotions",
        "world_intro": "🐾 Oh, it is Baba Yaga and Koschei!",
        "image": "16_baba_yaga_koschei_housework.png",
        "question": "Baba Yaga is nervous and worried, but Koschei seems miserable. Why?",
        "options": [
            {"text": "He should wash the dishes.", "correct": True},
            {"text": "He should to wash the floor.", "correct": False, "error": "SHOULD_HOUSEWORK", "meaning": "не знает форму глагола после should и путает wash the floor / wash the dishes; возможно, не понял лексику эмоций"},
            {"text": "He wants clean the dishes", "correct": False, "error": "WANTS_TO_HOUSEWORK_EMOTIONS", "meaning": "не знает, как использовать два глагола рядом, пропускает to и путает wash the dishes / clean the room; возможно, не понял лексику эмоций"},
        ],
    },
    {
        "id": 17,
        "topic": "IMPERATIVE_ROAD_SAFETY",
        "topic_ru": "Imperative; road safety and directions",
        "world_intro": "🐾 Wow! Now we are inside a comic book!",
        "image": "17_superhero_interactive_city_map.png",
        "question": "The super girl shows you the way. Which instructions are correct?",
        "options": [
            {"text": "Use the zebra crossing. Turn right. Walk on the pavement.", "correct": True},
            {"text": "Cross the pavement. Turn left. Walk through the parking zone.", "correct": False, "error": "ROAD_SAFETY_ROUTE", "meaning": "форму Imperative понимает, но путает дорожную лексику, направление движения и не читает маршрут по изображению"},
            {"text": "Wears a seat belt. Crosses the parking zone. Turns right.", "correct": False, "error": "IMPERATIVE_ROAD_SAFETY", "meaning": "не понимает форму Imperative и не различает дорожные инструкции для пешехода и лексику ситуации"},
        ],
    },
    {
        "id": 18,
        "topic": "FUTURE_ARRANGEMENT",
        "topic_ru": "Present Continuous for fixed future arrangements vs will / be going to",
        "image": "18_miles_meets_gwen_tuesday.png",
        "question": "Miles and Gwen made an appointment. What is Spiderman doing on Tuesday?",
        "options": [
            {"text": "He is meeting the super girl on Tuesday.", "correct": True},
            {"text": "He will meet the super girl on Tuesday.", "correct": False, "error": "ARRANGEMENT_VS_WILL", "meaning": "не различает будущее предсказание или решение и заранее согласованную встречу; фраза возможна в другом контексте, но не выражает проверяемую школьную функцию"},
            {"text": "He is going to meet the super girl on Tuesday.", "correct": False, "error": "ARRANGEMENT_VS_INTENTION", "meaning": "понимает будущее намерение, но не различает intention и fixed arrangement; фраза возможна в другом контексте"},
        ],
    },
    {
        "id": 19,
        "topic": "FUTURE_PLANS",
        "topic_ru": "be going to for plans and intentions; build a house / garden",
        "world_intro": "🐾 Hooray! Minecraft!",
        "image": "19_minecraft_build_house.png",
        "question": "It’s evening. What is the boys’ plan?",
        "options": [
            {"text": "They are going to build a house.", "correct": True},
            {"text": "They will build a house.", "correct": False, "error": "PLAN_VS_WILL", "meaning": "не различает заранее существующий план и другие функции will"},
            {"text": "They will build a garden.", "correct": False, "error": "PLAN_VS_WILL_GARDEN", "meaning": "не выбирает be going to для заранее существующего плана и путает лексику build a house / garden"},
        ],
    },
    {
        "id": 20,
        "topic": "FUTURE_DECISIONS",
        "topic_ru": "will for spontaneous decisions vs be going to / Present Continuous; help / suddenly / hurt / fall down",
        "image": "20_minecraft_creeper.png",
        "question": "Oh, no! It’s a Creeper! What does Steve say?",
        "options": [
            {"text": "I'll help you! He won’t hurt us.", "correct": True},
            {"text": "I'm going to help you! He won’t hurt us.", "correct": False, "error": "DECISION_VS_INTENTION", "meaning": "понимает глаголы действия, но путает решение, принятое сейчас, с заранее существующим намерением"},
            {"text": "I'm helping you in a minute! He won’t fall down.", "correct": False, "error": "DECISION_VS_ARRANGEMENT_ACTIONS", "meaning": "не различает спонтанное решение сейчас и заранее организованное действие в будущем, а также путает глаголы hurt / fall down"},
        ],
    },
]
