QUESTIONS = [
    {
        "id": 1,
        "topic": "NUMBERS",
        "topic_ru": "Numbers — числительные",
        "world_intro": "🐾 Гав! Начинаем путешествие. Смотри — восточный рынок! / Look — an eastern market!",
        "image": "01_eastern_market_doll_five.jpg",
        "question": "How much is the doll?",
        "translation": "Сколько стоит кукла?",
        "scene_hint": "The doll is five dollars.",
        "options": [
            {"text": "7", "correct": False, "error": "NUM_RECOGNITION", "meaning": "путает написанное числительное five"},
            {"text": "5", "correct": True},
            {"text": "6", "correct": False, "error": "NUM_RECOGNITION", "meaning": "путает написанное числительное five"},
        ],
    },
    {
        "id": 2,
        "topic": "NUMBERS",
        "topic_ru": "Numbers — числительные",
        "image": "02_eastern_market_lamp_eight.jpg",
        "question": "How much is the lamp?",
        "translation": "Сколько стоит лампа?",
        "options": [
            {"text": "7", "correct": False, "error": "NUM_RECOGNITION", "meaning": "путает написанное числительное eight"},
            {"text": "8", "correct": True},
            {"text": "9", "correct": False, "error": "NUM_RECOGNITION", "meaning": "путает написанное числительное eight"},
        ],
    },
    {
        "id": 3,
        "topic": "TO_BE",
        "topic_ru": "to be",
        "image": "03_eastern_princess_purple_dress.jpg",
        "question": "What colour is the doll's dress?",
        "translation": "Какого цвета платье куклы?",
        "options": [
            {"text": "The doll's dress are purple.", "correct": False, "error": "BE_IS_ARE", "meaning": "путает is и are"},
            {"text": "The doll's dress is purple.", "correct": True},
            {"text": "The doll's dress am purple.", "correct": False, "error": "BE_AM_IS", "meaning": "путает am и is"},
        ],
    },
    {
        "id": 4,
        "topic": "TO_BE",
        "topic_ru": "to be",
        "image": "04_eastern_princess_happy.jpg",
        "question": "Is she happy?",
        "translation": "Она счастлива?",
        "options": [
            {"text": "Yes, she is.", "correct": True},
            {"text": "Yes, she are.", "correct": False, "error": "BE_IS_ARE", "meaning": "путает is и are в коротком ответе"},
            {"text": "Yes, she isn't.", "correct": False, "error": "BE_NOT", "meaning": "путает утвердительную и отрицательную форму to be"},
        ],
    },
    {
        "id": 5,
        "topic": "HAVE_GOT",
        "topic_ru": "have got / has got",
        "world_intro": "🐾 Смотри! Мы в необычном городе животных! / An animal city!",
        "image": "05_animal_city_police_chips.jpg",
        "question": "Has he got chips?",
        "translation": "У него есть чипсы?",
        "options": [
            {"text": "Yes, he have.", "correct": False, "error": "HAVE_HAS_FORM", "meaning": "путает have и has"},
            {"text": "Yes, he hasn't.", "correct": False, "error": "HAVE_HAS_NOT", "meaning": "путает утвердительный и отрицательный короткий ответ с has got"},
            {"text": "Yes, he has.", "correct": True},
        ],
    },
    {
        "id": 6,
        "topic": "HAVE_GOT",
        "topic_ru": "have got / has got",
        "image": "06_animal_city_big_eyes.jpg",
        "question": "What have they got?",
        "translation": "Что у них есть?",
        "options": [
            {"text": "They have got big eyes.", "correct": True},
            {"text": "They has got big eyes.", "correct": False, "error": "HAVE_HAS_AGREEMENT", "meaning": "путает have и has с местоимением they"},
            {"text": "They got have big eyes.", "correct": False, "error": "HAVE_GOT_WORD_ORDER", "meaning": "нарушает порядок слов в have got"},
        ],
    },
    {
        "id": 7,
        "topic": "PRESENT_SIMPLE",
        "topic_ru": "Present Simple",
        "world_intro": "🐾 Вау! Anime City! / Мы в аниме-городе!",
        "image": "07_anime_city_girl_icecream.jpg",
        "question": "What does she like?",
        "translation": "Что ей нравится?",
        "options": [
            {"text": "He likes ice-cream.", "correct": False, "error": "PRONOUN_ERROR", "meaning": "путает местоимения he и she"},
            {"text": "She likes ice-cream.", "correct": True},
            {"text": "She like ice-cream.", "correct": False, "error": "PRESENT_SIMPLE_3SG", "meaning": "пропускает окончание -s в 3-м лице Present Simple"},
        ],
    },
    {
        "id": 8,
        "topic": "PRESENT_SIMPLE",
        "topic_ru": "Present Simple",
        "image": "08_anime_city_offer_icecream.jpg",
        "question": "Do you like ice-cream?",
        "translation": "Ты любишь мороженое?",
        "options": [
            {"text": "Yes, I do.", "correct": True},
            {"text": "Yes, I like.", "correct": False, "error": "PRESENT_SIMPLE_SHORT_ANSWER", "meaning": "не знает короткий ответ с do"},
            {"text": "Yes, I does.", "correct": False, "error": "DO_DOES_AGREEMENT", "meaning": "путает do и does с местоимением I"},
        ],
    },
    {
        "id": 9,
        "topic": "CAN",
        "topic_ru": "can / can't",
        "world_intro": "🐾 Смотри, какой красивый аниме-фэнтези мир!",
        "image": "09_fantasy_anime_flying_girl.jpg",
        "question": "Can Paimon fly?",
        "translation": "Паймон умеет летать?",
        "options": [
            {"text": "Yes, she can.", "correct": True},
            {"text": "Yes, she cans.", "correct": False, "error": "CAN_ADDS_S", "meaning": "добавляет -s к can"},
            {"text": "Yes, she is.", "correct": False, "error": "CAN_VS_BE", "meaning": "путает короткие ответы с can и to be"},
        ],
    },
    {
        "id": 10,
        "topic": "CAN",
        "topic_ru": "can / can't",
        "image": "10_fantasy_anime_climbing_traveler.jpg",
        "question": "Look! He can ...",
        "translation": "Смотри! Он умеет...",
        "options": [
            {"text": "climb", "correct": True},
            {"text": "climbs", "correct": False, "error": "CAN_BASE_VERB", "meaning": "не использует базовую форму глагола после can"},
            {"text": "climbing", "correct": False, "error": "CAN_BASE_VERB", "meaning": "ставит -ing форму после can"},
        ],
    },
    {
        "id": 11,
        "topic": "THERE_IS_ARE",
        "topic_ru": "there is / there are",
        "world_intro": "🐾 О! Старая школа магии! / A magic school!",
        "image": "11_magic_school_cat_on_bed.jpg",
        "question": "Look at the room. Choose the correct sentence.",
        "translation": "Посмотри на комнату. Выбери правильное предложение.",
        "options": [
            {"text": "There is a cat on the bed.", "correct": True},
            {"text": "There are a cat on the bed.", "correct": False, "error": "THERE_IS_ARE_NUMBER", "meaning": "путает there is и there are с единственным числом"},
            {"text": "There a cat is on the bed.", "correct": False, "error": "THERE_WORD_ORDER", "meaning": "нарушает порядок слов в there is"},
        ],
    },
    {
        "id": 12,
        "topic": "THERE_IS_ARE",
        "topic_ru": "there is / there are",
        "image": "12_magic_school_two_books_table.jpg",
        "question": "Choose the correct sentence.",
        "translation": "Выбери правильное предложение.",
        "options": [
            {"text": "There isn't three books on the table.", "correct": False, "error": "THERE_IS_ARE_NUMBER_NOT", "meaning": "путает isn't и aren't с множественным числом"},
            {"text": "There aren't three books on the table.", "correct": True},
            {"text": "There not three books are on the table.", "correct": False, "error": "THERE_WORD_ORDER_NOT", "meaning": "нарушает порядок слов в отрицательной конструкции there are"},
        ],
    },
    {
        "id": 13,
        "topic": "PREPOSITIONS",
        "topic_ru": "Prepositions of place — предлоги места",
        "image": "13_magic_school_owl_under_chair.jpg",
        "question": "Where is the owl?",
        "translation": "Где сова?",
        "options": [
            {"text": "There is an owl on the chair.", "correct": False, "error": "PREPOSITION_ON_UNDER", "meaning": "путает on и under"},
            {"text": "There is an owl under the chair.", "correct": True},
            {"text": "There is an owl in the chair.", "correct": False, "error": "PREPOSITION_IN_UNDER", "meaning": "путает in и under"},
        ],
    },
    {
        "id": 14,
        "topic": "PREPOSITIONS",
        "topic_ru": "Prepositions of place — предлоги места",
        "image": "14_magic_school_golden_ball_cupboard.jpg",
        "question": "What can you see?",
        "translation": "Что ты видишь?",
        "options": [
            {"text": "There is a golden Snitch in the cupboard.", "correct": True},
            {"text": "There is a golden Snitch on the cupboard.", "correct": False, "error": "PREPOSITION_IN_ON", "meaning": "путает in и on"},
            {"text": "There is a golden Snitch under the cupboard.", "correct": False, "error": "PREPOSITION_IN_UNDER", "meaning": "путает in и under"},
        ],
    },
    {
        "id": 15,
        "topic": "PRESENT_CONTINUOUS",
        "topic_ru": "Present Continuous",
        "world_intro": "🐾 А вот и «Ну, погоди!»!",
        "image": "15_nu_pogodi_wolf_tshirt.jpg",
        "question": "What is he wearing?",
        "translation": "Во что он одет?",
        "options": [
            {"text": "He wearing a T-shirt.", "correct": False, "error": "PRESENT_CONT_MISSING_BE", "meaning": "пропускает to be в Present Continuous"},
            {"text": "He is wearing a T-shirt.", "correct": True},
            {"text": "He is wear a T-shirt.", "correct": False, "error": "PRESENT_CONT_MISSING_ING", "meaning": "не использует -ing форму в Present Continuous"},
        ],
    },
    {
        "id": 16,
        "topic": "PRESENT_CONTINUOUS",
        "topic_ru": "Present Continuous",
        "image": "16_nu_pogodi_hare_eating.jpg",
        "question": "Choose the correct sentence.",
        "translation": "Выбери правильное предложение.",
        "options": [
            {"text": "He isn't dancing.", "correct": True},
            {"text": "He not dancing.", "correct": False, "error": "PRESENT_CONT_MISSING_BE", "meaning": "пропускает is в отрицании Present Continuous"},
            {"text": "He does not dancing.", "correct": False, "error": "PRESENT_CONT_DOES_INSTEAD_BE", "meaning": "использует does вместо to be в Present Continuous"},
        ],
    },
    {
        "id": 17,
        "topic": "PLURAL",
        "topic_ru": "Plural nouns — множественное число",
        "world_intro": "🐾 Добро пожаловать в мир Roblox!",
        "image": "17_block_game_three_foxes.jpg",
        "question": "What can you see?",
        "translation": "Что ты видишь?",
        "options": [
            {"text": "three fox", "correct": False, "error": "PLURAL_MISSING_S", "meaning": "не образует множественное число существительного"},
            {"text": "three foxes", "correct": True},
            {"text": "three foxs", "correct": False, "error": "PLURAL_WRONG_ENDING", "meaning": "понимает необходимость множественного числа, но не знает окончание -es после x"},
        ],
    },
    {
        "id": 18,
        "topic": "PLURAL",
        "topic_ru": "Plural nouns — множественное число",
        "image": "18_block_game_two_mice.jpg",
        "question": "What can you see?",
        "translation": "Что ты видишь?",
        "options": [
            {"text": "two mice", "correct": True},
            {"text": "two mouses", "correct": False, "error": "IRREGULAR_PLURAL", "meaning": "не знает неправильную форму mouse → mice"},
            {"text": "two mise", "correct": False, "error": "PLURAL_SPELLING", "meaning": "знает необычную форму множественного числа, но ошибается в написании mice"},
        ],
    },
    {
        "id": 19,
        "topic": "DEMONSTRATIVES",
        "topic_ru": "this / that / these / those",
        "world_intro": "🐾 Мы добрались до Minecraft! Осталось совсем чуть-чуть!",
        "image": "19_cube_world_this_bed.jpg",
        "question": "This is Steve's bed. What does he say?",
        "translation": "Это кровать Стива. Что он говорит?",
        "options": [
            {"text": "This is my bed.", "correct": True},
            {"text": "These is my bed.", "correct": False, "error": "THIS_THESE_NUMBER", "meaning": "путает this и these по числу"},
            {"text": "That is my bed.", "correct": False, "error": "THIS_THAT_DISTANCE", "meaning": "путает this и that по расстоянию"},
        ],
    },
    {
        "id": 20,
        "topic": "DEMONSTRATIVES",
        "topic_ru": "this / that / these / those",
        "image": "20_cube_world_those_pigs.jpg",
        "question": "Look!",
        "translation": "Смотри!",
        "options": [
            {"text": "That are my pigs.", "correct": False, "error": "THAT_THOSE_NUMBER", "meaning": "путает that и those по числу"},
            {"text": "Those are my pigs.", "correct": True},
            {"text": "These are my pigs.", "correct": False, "error": "THESE_THOSE_DISTANCE", "meaning": "путает these и those по расстоянию"},
        ],
    },
]

TOPIC_ORDER = [
    "NUMBERS", "TO_BE", "HAVE_GOT", "PRESENT_SIMPLE", "CAN",
    "THERE_IS_ARE", "PREPOSITIONS", "PRESENT_CONTINUOUS", "PLURAL", "DEMONSTRATIVES"
]
